name: 'Bluejay Simulation Action'
description: 'Queue and optionally wait for Bluejay simulation runs to gate CI.'
author: 'Bluejay Intelligence Inc.'
branding:
  icon: 'play'
  color: 'blue'

inputs:
  api_key:
    description: 'Bluejay API key'
    required: true
  simulation_id:
    description: 'Bluejay simulation ID to run'
    required: true
  prompt_id:
    description: 'Prompt UUID associated with this run'
    required: false
  knowledge_base_id:
    description: 'Knowledge base UUID associated with this run'
    required: false
  digital_human_ids:
    description: 'Comma-separated list of Digital human IDs to be used'
    required: false
  phone_number:
    description: 'Optional phone number to be used in this simulation run'
    required: false
  sip_uri:
    description: 'Optional SIP URI to be used in this simulation run'
    required: false

  wait_for_results:
    description: 'If true, wait for simulation results and fail CI based on score'
    required: false
    default: 'true'
  min_score:
    description: 'Minimum required overall score (0–100). Build fails below this.'
    required: false
    default: '80'
  poll_interval_seconds:
    description: 'Polling interval in seconds while waiting for results'
    required: false
    default: '10'
  timeout_seconds:
    description: 'Maximum seconds to wait for simulation completion'
    required: false
    default: '1500'

outputs:
  simulation-run-id:
    description: 'ID of the queued Bluejay simulation run'
  final-status:
    description: 'Final status of the simulation (completed/failed/cancelled)'
  score:
    description: 'Overall score from the simulation results (0–100)'
  report-url:
    description: 'Link to the Bluejay simulation report (if available)'

runs:
  using: 'node20'
  main: 'dist/index.js'
